//
//  ListOrdersInteractorTests.swift
//  CleanStore
//
//  Created by Waratnan Suriyasorn on 4/8/2559 BE.
//  Copyright (c) 2559 M Warat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import CleanStore
import XCTest

class ListOrdersInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListOrdersInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListOrdersInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListOrdersInteractor()
  {
    sut = ListOrdersInteractor()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testFetchOrdersShouldAskOrdersWorkerToFetchOrders()
  {
    // Given
    let listOrdersInteractorOutputSpy = ListOrdersInteractorOutputSpy()
    sut.output = listOrdersInteractorOutputSpy
    let ordersWorkerSpy = OrdersWorkerSpy()
    sut.worker = ordersWorkerSpy
    
    // When
    let request = ListOrders_FetchOrders_Request()
    sut.fetchOrders(request)
    
    // Then
    XCTAssert(ordersWorkerSpy.fetchOrdersCalled, "FetchOrders() should ask OrdersWorker to fetch orders")
    XCTAssert(listOrdersInteractorOutputSpy.presentFetchedOrdersCalled, "FetchOrders() should ask presenter to format orders result")
  }
}
