//
//  ListOrdersWorker.swift
//  CleanStore
//
//  Created by Waratnan Suriyasorn on 4/8/2559 BE.
//  Copyright (c) 2559 M Warat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class ListOrdersWorker
{
  // MARK: Business Logic
  
  func doSomeWork()
  {
    // NOTE: Do the work
  }
}
