//
//  ListOrdersModels.swift
//  CleanStore
//
//  Created by Waratnan Suriyasorn on 4/8/2559 BE.
//  Copyright (c) 2559 M Warat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct ListOrdersRequest
{
}

struct ListOrdersResponse
{
}

struct ListOrdersViewModel
{
}

struct ListOrders_FetchOrders_Request
{
}

struct ListOrders_FetchOrders_Response
{
  var orders: [Order]
}