//
//  ShowOrderInteractor.swift
//  CleanStore
//
//  Created by Waratnan Suriyasorn on 4/11/2559 BE.
//  Copyright (c) 2559 M Warat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ShowOrderInteractorInput
{
  func getOrder(request: ShowOrderRequest)
  var order: Order! { get set }
}

protocol ShowOrderInteractorOutput
{
  func presentOrder(response: ShowOrderResponse)
}

class ShowOrderInteractor: ShowOrderInteractorInput
{
  var output: ShowOrderInteractorOutput!
  
  var order: Order!
  // MARK: Business logic
  
//  func doSomething(request: ShowOrderRequest)
//  {
//    // NOTE: Create some Worker to do the work
//    
//    worker = ShowOrderWorker()
//    worker.doSomeWork()
//    
//    // NOTE: Pass the result to the Presenter
//    
//    let response = ShowOrderResponse()
//    output.displayOrder(response)
//  }
  
  func getOrder(request: ShowOrderRequest) {
    let response = ShowOrderResponse(order: order)
    output.presentOrder(response)
  }
}
