//
//  ShowOrderPresenter.swift
//  CleanStore
//
//  Created by Waratnan Suriyasorn on 4/11/2559 BE.
//  Copyright (c) 2559 M Warat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ShowOrderPresenterInput
{
  func presentOrder(response: ShowOrderResponse)
}

protocol ShowOrderPresenterOutput: class
{
  func displayOrder(viewModel: ShowOrderViewModel)
}

class ShowOrderPresenter: ShowOrderPresenterInput
{
  weak var output: ShowOrderPresenterOutput!
  
  let dateFormatter: NSDateFormatter = {
    let dateFormatter = NSDateFormatter()
    dateFormatter.dateStyle = .ShortStyle
    dateFormatter.timeStyle = NSDateFormatterStyle.NoStyle
    return dateFormatter
  }()
  
  let currencyFormatter: NSNumberFormatter = {
    let currencyFormatter = NSNumberFormatter()
    currencyFormatter.numberStyle = .CurrencyStyle
    return currencyFormatter
  }()
  
  // MARK: Presentation logic
  
  func presentOrder(response: ShowOrderResponse)
  {
    
    
    let order = response.order
    let date = dateFormatter.stringFromDate(order.date!)
    let total = currencyFormatter.stringFromNumber(order.total!)
    let displayerOrder = ShowOrderViewModel.DisplayedOrder(id: order.id!, date: date, email: order.email!, name: "\(order.firstName!) \(order.lastName!)", total: total!)
    
    let viewModel = ShowOrderViewModel(displayedOrder: displayerOrder)
    output.displayOrder(viewModel)
        
  }
  
}
