//
//  ShowOrderViewController.swift
//  CleanStore
//
//  Created by Waratnan Suriyasorn on 4/11/2559 BE.
//  Copyright (c) 2559 M Warat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ShowOrderViewControllerInput
{
  func displayOrder(viewModel: ShowOrderViewModel)
}

protocol ShowOrderViewControllerOutput
{
  func getOrder(request: ShowOrderRequest)
  var order: Order! { get set }
}

class ShowOrderViewController: UIViewController, ShowOrderViewControllerInput
{
  var output: ShowOrderViewControllerOutput!
  var router: ShowOrderRouter!
  
  @IBOutlet weak var orderIDLabel: UILabel!
  @IBOutlet weak var orderDateLabel: UILabel!
  @IBOutlet weak var orderEmailLabel: UILabel!
  @IBOutlet weak var orderNameLabel: UILabel!
  @IBOutlet weak var orderTotalLabel: UILabel!
  
  // MARK: Object lifecycle
  
  override func awakeFromNib()
  {
    super.awakeFromNib()
    ShowOrderConfigurator.sharedInstance.configure(self)
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    getOrderOnLoad()
  }
  
  // MARK: Event handling
  
  func getOrderOnLoad()
  {
    // NOTE: Ask the Interactor to do some work
    
    let request = ShowOrderRequest()
    output.getOrder(request)
  }
  
  // MARK: Display logic
  
  func displayOrder(viewModel: ShowOrderViewModel) {
    // NOTE: Display the result from the Presenter
    let displayedOrder = viewModel.displayedOrder
    
    orderIDLabel.text = displayedOrder.id
    orderDateLabel.text = displayedOrder.date
    orderEmailLabel.text = displayedOrder.email
    orderNameLabel.text = displayedOrder.name
    orderTotalLabel.text = displayedOrder.total
    
  }
}
