//
//  ShowOrderViewControllerTests.swift
//  CleanStore
//
//  Created by Waratnan Suriyasorn on 4/11/2559 BE.
//  Copyright (c) 2559 M Warat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import CleanStore
import XCTest

class ShowOrderViewControllerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ShowOrderViewController!
  var window: UIWindow!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    window = UIWindow()
    setupShowOrderViewController()
  }
  
  override func tearDown()
  {
    window = nil
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupShowOrderViewController()
  {
    let bundle = NSBundle.mainBundle()
    let storyboard = UIStoryboard(name: "Main", bundle: bundle)
    sut = storyboard.instantiateViewControllerWithIdentifier("ShowOrderViewController") as! ShowOrderViewController
  }
  
  func loadView()
  {
    window.addSubview(sut.view)
    NSRunLoop.currentRunLoop().runUntilDate(NSDate())
  }
  
  // MARK: Test doubles
  class ShowOrderViewControllerOutputSpy: ShowOrderViewControllerOutput {
    var getOrderCalled = false
    var order: Order!
    
    func getOrder(request: ShowOrderRequest) {
      getOrderCalled = true
    }
  }
  
  // MARK: Tests
  
  func testShouldGetOrderObjectWhenViewIsLoad()
  {
    // Given
    let showOrderViewControllerOutputSpy = ShowOrderViewControllerOutputSpy()
    sut.output = showOrderViewControllerOutputSpy
    
    // When
    loadView()
    
    // Then
    XCTAssert(showOrderViewControllerOutputSpy.getOrderCalled, "Should get orders when the view is loaded")
  }

  func testShouldDisplayedOrder() {
    // Given
    
    // When
    
    // Then
  }
}
