//
//  ShowOrderPresenterTests.swift
//  CleanStore
//
//  Created by Waratnan Suriyasorn on 4/11/2559 BE.
//  Copyright (c) 2559 M Warat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import CleanStore
import XCTest

class ShowOrderPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ShowOrderPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupShowOrderPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupShowOrderPresenter()
  {
    sut = ShowOrderPresenter()
  }
  
  // MARK: Test doubles
  class ShowOrderPresenterOutputSpy:ShowOrderPresenterOutput {
    var displayOrderCalled = false
    var showOrderViewModel: ShowOrderViewModel!
    
    func displayOrder(viewModel: ShowOrderViewModel) {
      displayOrderCalled = true
      showOrderViewModel = viewModel
    }
  }
  // MARK: Tests
  
  func testPresentOrderShouldFormatOrderForDisplay()
  {
    // Given
    let showOrderPresenterOutputSpy = ShowOrderPresenterOutputSpy()
    sut.output = showOrderPresenterOutputSpy
    
    let dateComponents = NSDateComponents()
    dateComponents.year = 2007
    dateComponents.month = 6
    dateComponents.day = 29
    
    let date = NSCalendar.currentCalendar().dateFromComponents(dateComponents)!
    
    let order = Order(id: "abc123", date: date, email: "amy.apple@clean-swift.com", firstName: "Amy", lastName: "Apple", total: NSDecimalNumber(string: "1.23"))
    
    let response = ShowOrderResponse(order: order)
    
    // When
    sut.presentOrder(response)
    
    // Then
    let displayedOrder = showOrderPresenterOutputSpy.showOrderViewModel.displayedOrder
    
    XCTAssertEqual(displayedOrder.id, "abc123", "Presenting fetched orders should properly format order ID")
    XCTAssertEqual(displayedOrder.date, "6/29/07", "Presenting fetched orders should properly format order date")
    XCTAssertEqual(displayedOrder.email, "amy.apple@clean-swift.com", "Presenting fetched orders should properly format email")
    XCTAssertEqual(displayedOrder.name, "Amy Apple", "Presenting fetched orders should properly format name")
    XCTAssertEqual(displayedOrder.total, "$1.23", "Presenting fetched orders should properly format total")
  }
  
  func testPresentOrderShouldAskViewControllerToDisplayOrder()
  {
    // Given
    let showOrderPresenterOutputSpy = ShowOrderPresenterOutputSpy()
    sut.output = showOrderPresenterOutputSpy
    
    let order = Order(id: "abc123", date: NSDate(), email: "amy.apple@clean-swift.com", firstName: "Amy", lastName: "Apple", total: NSDecimalNumber(string: "1.23"))
    
    let response = ShowOrderResponse(order: order)
    
    // When
    sut.presentOrder(response)
    
    // Then
    XCTAssert(showOrderPresenterOutputSpy.displayOrderCalled, "Presenting get order should ask view controller to display them")
  }
}
